### ISSUE TITLE
Display Fall 2020 unique joining instructions

### ISSUE THREAD

**Issue by TechSolomon** [uaf-cs/nookbot#7]
Demonstrate with `!help` that class signups are done over the web interface at [https://nookbot.katlyn.dev/](https://nookbot.katlyn.dev/). 

> NookBot - Utilties for UAF-CS
> by UAF Students
> 
> Commands:
>   !help - This help text
>   **!joinclass - 🆕 Join classes with [https://nookbot.katlyn.dev/](https://nookbot.katlyn.dev/)**
>   !addclasses - Add classes in bulk from a CSV file
>   !fact - Gives a random fact
>   !cat - Gives a random cat
>   !dog - Gives a random dog
>   !hotdog - Gives a random hotdog
>   !roll - No description
> 
> Type !help <command> for more info on a command.

-----

### TODO:
- [ ] Recreate the `!joinclass` command or something similar. 
_Optional: Send a direct message to students upon joining/leaving classes._ 
- [ ] Update the `!help` command text and description.
- [ ] Create another announcement for students if they have not already joined their classes.
